env:
  es6: true
  browser:true

extends: eslint:recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parserOptions:
  ecmaVersion: 2018
  sourceType: module

plugins:
  fp

rules:
  comma-dangle: 0
  max-lines:
  - warn
  - 200
  max-lines-per-function:
  - warn
  - 20
  complexity:
  - warn
  - 5
  max-nested-callbacks:
  - warn
  - 2  
  max-depth:
  - warn
  - 3
  max-params:
  - warn
  - 2
  no-param-reassign: warn
  fp/no-mutation: warn
  fp/no-mutating-assign: warn
  fp/no-mutating-methods: warn
  fp/no-mutation: warn
  fp/no-let: warn
  fp/no-this: warn
  fp/no-loops: warn
  fp/no-mutating-assign: warn
  fp/no-mutating-methods: warn
  fp/no-mutation: warn
  fp/no-delete: warn
  fp/no-throw: warn